version: '3.9'

services:
  app:
    build: 
      context: .
    image: app
    command: uvicorn main:app --reload --port=8080
    ports:
      - 8080:8080
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    volumes:
      - .:/app

  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data:ro

volumes:
  db_data:
